### ISSUE TITLE
Keyboard.poll()

### ISSUE THREAD

**Issue by httpdigest** [kappaOne/lwjglx#3]
Will Keyboard.poll() be supported?
Themable Widget Library surprisingly works pretty well with lwjglx and LWJGL 3, except for keyboard input. :)

**Comment by kappaOne** [comment]
hmm, from my testing this seems to be a problem only on linux for some reason, it appears that the GLFWKeyCallback is not firing for whatever reason, although GLFWCharCallback is firing. Still looking into it but something somewhere in the Display class seems broken which is causing this to only appear on linux. Ran a standalone test and GLFWKeyCallback does work. very odd.

**Comment by httpdigest** [comment]
Windows would fine for me for the time being. I just suggested `Keyboard.poll()` be implemented at all, since from the version I cloned yesterday that just had a `// TODO` in it. :)

**Comment by Spasi** [comment]
> hmm, from my testing this seems to be a problem only on linux for some reason, it appears that the GLFWKeyCallback is not firing, although GLFWCharCallback is firing.

This is a [known issue](https://github.com/glfw/glfw/issues/548) with the current GLFW nightlies on Linux.

LWJGL builds currently use GLFW & OpenAL Soft nightly builds, which was convenient when I set it up, but quite risky. I'll try to change this tomorrow.

**Comment by Spasi** [comment]
The builds have been updated, does it work for you now?

**Comment by kappaOne** [comment]
thanks spasi, works great now

**Comment by httpdigest** [comment]
I can confirm this works too, now.
