### ISSUE TITLE
Implement Mouse.setNativeCursor()

### ISSUE THREAD

**Issue by httpdigest** [kappaOne/lwjglx#4]
Hey kappa,

TWL runs now out-of-the-box with lwjglx. Great job!
And also thanks for adding the EXTTextureRectangle extension.

There is just one more thing: Can we do Mouse.setNativeCursor() make use GLFW.glfwSetCursor()?

Cheers,
Kai

**Comment by kappaOne** [comment]
Mouse.setNativeCursor is now implement using glfwSetCursor. No animated cursor support yet, but can be added if needed by anyone

**Comment by httpdigest** [comment]
Works. Thanks!
