### ISSUE TITLE
Mouse wheele support

### ISSUE THREAD

**Issue by httpdigest** [kappaOne/lwjglx#5]
I did some experiments with the mouse wheele and TWL. It seems that GLFW mousewheele events are currently not propagated properly.

**Comment by sriharshachilakapati** [comment]
The issue is with the implementation. The `getDWheel()` method has not yet been implemented.

**Comment by kappaOne** [comment]
thx, implemented Mouse.getDWheel() and Mouse.getEventDWheel() methods.

**Comment by httpdigest** [comment]
Awesome! Works now as expected. :)
